version: '3.9'

networks:
    frontend:
        driver: ${NETWORKS_DRIVER}
    backend:
        driver: ${NETWORKS_DRIVER}

services:
    nginx:
        build:
            context: ./nginx
        container_name: nginx
        volumes:
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
            - ${NGINX_FASTCGI_PARAM}:/etc/nginx/fastcgi_params
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
        depends_on:
            - php-fpm
        networks:
            - frontend
            - backend
    php-fpm:
        build:
            context: ./php-fpm
        container_name: php-fpm
        volumes:
            - ./php-fpm/php7.4.ini:/usr/local/etc/php/php.ini
            - ./php-fpm/laravel.ini:/usr/local/etc/php/conf.d/laravel.ini
            - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
        expose:
            - "9000"
        extra_hosts:
            - "dockerhost:${DOCKER_HOST_IP}"
        networks:
            - backend
    mysql:
        build:
            context: ./mysql
        container_name: mysql
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
        ports:
            - "${MYSQL_PORT}:3306"
        networks:
            - backend
    redis:
        build:
            context: ./redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - backend
    phpmyadmin:
        build:
            context: ./phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8090:80"
        environment:
            - PMA_ARBITRARY=1
        networks:
            - backend